### ISSUE TITLE
MVP tracking issue

### ISSUE THREAD

**Issue by jmintb** [TeaInSpace/ame#69]
This issue lists the features we are planning to implement for a minimally viable version of AME.

- [x] Run your model training with zero changes to your python code.
- [x] Execute tasks remotely, but display output and downloads artifacts to simulate local execution.
- [ ] Automatic setup of python versions and dependencies using any common python dependency manager.
- [x] Scale the infrastructure used for the model training in a code effective manner.
- [x] Provide simple authentication when using the CLI.
- [x] Support injecting secrets during Task execution.
- [x] Support configuration environment variables for Task execution.
- [ ] Adjust the resource requirements to fit the needs of your training
automatically, for example if you training fails due to lack of ram, the task
will be rescheduled and more ram provisioned.
- [x] Schedule reoccuring model traning based on project specifications.
- [x] Configure how your project is run declaritively in a config file.
- [ ] Support outputting artifacts from your training to an arbitrary location
such as an s3 bucket.
- [x] Support storing artifacts within AME's own object storage.
- [ ] Deployable with a terraform setup supplied from the project repository.
- [ ] AME will be able to track projects in your git repositories and detect
when they have an AME config file. Allowing you to simply place your config file
in the repo like you would with CI/CD configuration and let AME take care of the
rest.
- [ ] Display project runs in a graphical UI, perhaps using mlflow.
- [ ] Support using Jupyterlab with AME.
- [ ] Support using custom images.
- [ ] Support overriding default workflow behavior.
