### ISSUE TITLE
Git repository tracking

### ISSUE THREAD

**Issue by jmintb** [TeaInSpace/ame#92]
## Context

One of AME's key value propositions is a [Gitops](https://about.gitlab.com/topics/gitops/) like approach for machine learning operations. Using a version control repository as a single source of truth for all or most of the configuration. It is therefore important that AME can track and ingest configuration from one or more Git repositories. 

### Why not use an existing Gitops tool?

It would be quite convenient to not re-implement this functionalty and use someling like ArgoCD. The problem is that AME has different needs for tracking files compared to ArgoCD. Users of AME should be oblivious to the internals and will expect that an AME file is detected just like any other CI file. ArgoCD would require users to define Kubernetes resources instead of or along side an AME file. AME also needs to be able to track aspects of Git that ArgoCD does not supported at the moment, such as the latest tag and Git host specific events such as merge requests.

### Other version control systems

There are other version control systems worth considering, most notably [mercurial](https://www.mercurial-scm.org/). AME will be focused on Git for now, but the internal architecture for tracking projects under version control will be kept as agnostic as possible to what type of version control is used. Thereby ensuring that support for other version control systems can be implemented in the future.

#### Polling vs webhooks

AME will need to support polling a Git repository every few minutes  and listening for events with web hooks from the Git host. This issue is focused on the former as polling is required as a fall back in all cases and it is the simplest way support this feature. Webhooks and other forms of integration will be left for the future with #79.

#### How a user will setup a repository for Git tracking

The process of tracking a repository in Git is as follows.

1. (For private repositories) add a secret required for accessing the intended repository to AME.
2. Add one or multiple repositories as project sources through the CLI or web interface.

#### Internal architecture

This issue will introduce the notion of project sources and projects as custom resource definitions. Project sources are intended to define sources for AME to check for source files. Initially there will only be one type of source Git, but this will expand in the future.

Projects will all of AME's configuration and will essentially be what is contained in an AME file. As outlined in the diagram below a separate Project object will be generated for every branch containing an AME file. This will allow for AME to treat branches differently when needed, for example there will probably be a need to have a designated main/protected branch for production deployments. 

![AME Architecture drawio](https://user-images.githubusercontent.com/10332534/208942951-2cfffdbd-ddb2-4843-bf68-c58f5b412e55.png)

### Acceptance criteria:
- [x] AME has a project source CRD and controller with support for Git repositories as a project source.
- [x] AME can use secrets as tokens for private git repositories.
- [x] the AME CLI can create project sources pointing to a git repository.
- [x] AME can track a project in Git.
